# Example showing a matrix job and a run-after-build job that only runs if
# there's a failure


name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install CMSIS Toolbox
        run: |
          wget https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/download/2.1.0/cmsis-toolbox-linux-amd64.tar.gz
          tar -xvzf cmsis-toolbox-linux-amd64.tar.gz
          echo ${PWD}/cmsis-toolbox-linux-amd64/bin >> $GITHUB_PATH
          cpackget --version

      - name: Install Memfault CMSIS Pack
        run: |
          echo $PATH
          # note: installing the non-https pidx, their cert is expired
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget add --verbose --agree-embedded-license Memfault::FirmwareSDK
          cpackget list
